sfdx-source/mutex/main/schema/objects/Mutex__c/Mutex__c.object-meta.xml
<CustomObject>
    <label>Mutex</label>
    <nameField>
        <displayFormat>MUTEX-{0000}</displayFormat>
        <label>Mutex Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mutex</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/AsyncClassName__c.field-meta.xml
<CustomField>
    <fullName>AsyncClassName__c</fullName>
    <label>Async Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <externalId>true</externalId>
    <label>Job Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <label>Job Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INACTIVE</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/ParametersSerialized__c.field-meta.xml
<CustomField>
    <fullName>ParametersSerialized__c</fullName>
    <description>If the async process requires initialization parameters, then this field represents the serialized form of those parameters.</description>
    <inlineHelpText>If the async process requires initialization parameters, then this field represents the serialized form of those parameters.</inlineHelpText>
    <label>Parameters Serialized</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/mutex/main/classes/services/MUTEX_ServiceImpl.cls
public inherited sharing class MUTEX_ServiceImpl
    implements MUTEX_IService
{
    public void turnMutexOn(String jobName)
    {
    	if ( String.isBlank(jobName) )
        {
            return;
        }

        IApplicationSObjectUnitOfWork uow = new ApplicationSObjectUnitOfWork(new List<Schema.SObjectType> { Mutex__c.sObjectType });

        MUTEX_IDomain mutexDomain = MUTEX_Domain.newInstance( selectByJobName( new List<String>{ jobName }) );

        mutexDomain.turnMutexOn(jobName, uow);

        uow.commitWork();
    }

    public void turnMutexOff(String jobName)
    {
    	if ( String.isBlank(jobName) )
        {
            return;
        }

        IApplicationSObjectUnitOfWork uow = new ApplicationSObjectUnitOfWork(new List<Schema.SObjectType> { Mutex__c.sObjectType });

        MUTEX_IDomain mutexDomain = MUTEX_Domain.newInstance( selectByJobName( new List<String>{ jobName }) );

        mutexDomain.turnMutexOff(jobName, uow);

        uow.commitWork();
    }

    public void setupMutexForJob( MUTEX_ServiceParameters params )
    {
        if ( String.isBlank(params.jobName) || params.asyncClassToRun == null )
        {
            return;
        }

        IApplicationSObjectUnitOfWork uow = new ApplicationSObjectUnitOfWork(new List<Schema.SObjectType> { Mutex__c.sObjectType });

        Mutex__c rec = new Mutex__c();

        rec.AsyncClassName__c = params.asyncClassToRun.getName();
        rec.JobId__c = params.jobName;
        rec.JobStatus__c = MUTEX_Domain.STATUS_CODES.INACTIVE.name();

        if (params.batchSize != null)
        {
            rec.BatchSize__c = params.batchSize;
        }
        
        if (params.initializationParameters != null)
        {
            rec.ParametersSerialized__c = JSON.serialize(params.initializationParameters);
        }

        uow.registerNew(rec);

        uow.commitWork();
    }

    public void setupMutexForJobIfNeeded( MUTEX_ServiceParameters params )
    {
        if (selectByJobName(new List<String>{params.jobName}).isEmpty())
        {
            setupMutexForJob(params);
        }
    }

    @TestVisible
    private static List<Mutex__c> selectByJobName(List<String> jobNames)
    {
        return jobNames != null 
                ? [select Id, Name, JobId__c, AsyncClassName__c, JobStatus__c, ParametersSerialized__c from Mutex__c where JobId__c in :jobNames] 
                : new List<Mutex__c>();
    }
}