sfdx-source/mutex/main/schema/objects/Mutex__c/Mutex__c.object-meta.xml
<CustomObject>
    <label>Mutex</label>
    <nameField>
        <displayFormat>MUTEX-{0000}</displayFormat>
        <label>Mutex Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mutex</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/AsyncClassName__c.field-meta.xml
<CustomField>
    <fullName>AsyncClassName__c</fullName>
    <label>Async Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/mutex/main/schema/objects/Mutex__c/fields/JobStatus__c.field-meta.xml
<CustomField>
    <fullName>JobStatus__c</fullName>
    <label>Job Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INACTIVE</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/mutex/test/classes/MutexTestDummyBatchable.cls
public with sharing class MutexTestDummyBatchable 
    implements Database.Batchable<sObject>
{
    public static final String MUTEX_JOB_ID_DUMMY_BATCH = 'UnitTestDummyBatch';

    public Database.QueryLocator start(Database.BatchableContext bc) 
    {
        String query = 'select id, ' + Mutex__c.AsyncClassName__c + ', ' + Mutex__c.JobStatus__c 
                        + ' from ' + Mutex__c.SObjectType 
                        + ' where ' + Mutex__c.AsyncClassName__c + ' = \'' + MutexTestDummyBatchable.class + '\'';
        System.debug('MutexTestDummyBatchable query = ' + query);
        return Database.getQueryLocator( query );
    }
    
    public void execute(Database.BatchableContext bc, List<Mutex__c> scope)
    {
        // process each batch of records
        system.debug('Batch Job launched');
    }
    
    /* 
     * updates MutexDummyBatch record JobStatus__c to Mutex.STATUS_CODES.INACTIVE.name() 
     */
    public void finish(Database.BatchableContext bc)
    {
        MutexService.turnMutexOff( MUTEX_JOB_ID_DUMMY_BATCH );
    }
}